/******************************************************************************/
/****        Generated by IBExpert 2023.4.14.1 26/06/2026 15:28:40         ****/
/******************************************************************************/

SET SQL DIALECT 3;

SET NAMES WIN1252;

SET CLIENTLIB 'C:\Program Files\Firebird\Firebird_4_0\WOW64\fbclient.dll';

CREATE DATABASE '127.0.0.1/3050:C:\AulaBD\PROJETOFINAL\SISTEMANOTASFISCAIS.fdb'
USER 'SYSDBA' PASSWORD 'masterkey'
PAGE_SIZE 16384
DEFAULT CHARACTER SET WIN1252 COLLATION WIN1252;



/******************************************************************************/
/****                               Domains                                ****/
/******************************************************************************/

CREATE DOMAIN DM_CIDADE AS
VARCHAR(60)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_DOCUMENTO AS
VARCHAR(10)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_DOCUMENTOCLIENTE AS
VARCHAR(20)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_ENDERECO AS
VARCHAR(100)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_NOMECLIENTE AS
VARCHAR(120)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_PRODUTO AS
VARCHAR(100)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_TELEFONE AS
VARCHAR(15)
NOT NULL
COLLATE WIN_PTBR;

CREATE DOMAIN DM_UF AS
VARCHAR(2)
NOT NULL
COLLATE WIN_PTBR;



/******************************************************************************/
/****                              Generators                              ****/
/******************************************************************************/

CREATE GENERATOR GEN_TALIQUOTAFEDERAL_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TALIQUOTAFEDERAL_ID TO 0;

CREATE GENERATOR GEN_TALIQUOTAICMS_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TALIQUOTAICMS_ID TO 0;

CREATE GENERATOR GEN_TCIDADE_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TCIDADE_ID TO 0;

CREATE GENERATOR GEN_TCLIENTE_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TCLIENTE_ID TO 0;

CREATE GENERATOR GEN_TNOTAFISCALITEM_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TNOTAFISCALITEM_ID TO 0;

CREATE GENERATOR GEN_TNOTAFISCAL_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TNOTAFISCAL_ID TO 0;

CREATE GENERATOR GEN_TPRODUTO_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TPRODUTO_ID TO 0;

CREATE GENERATOR GEN_TTIPODOCUMENTO_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TTIPODOCUMENTO_ID TO 0;

CREATE GENERATOR GEN_TUF_ID START WITH 1 INCREMENT BY 1;
SET GENERATOR GEN_TUF_ID TO 0;



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

CREATE PROCEDURE SP_APURACAO_IMPOSTOS (
    PR_MES INTEGER,
    PR_ANO INTEGER)
RETURNS (
    BDFATURAMENTOBRUTO NUMERIC(15,2),
    BDTOTALICMS NUMERIC(15,2),
    BDTOTALPIS NUMERIC(15,2),
    BDTOTALCOFINS NUMERIC(15,2))
AS
BEGIN
  SUSPEND;
END^






SET TERM ; ^



/******************************************************************************/
/****                                Tables                                ****/
/******************************************************************************/



CREATE TABLE TALIQUOTAFEDERAL (
    BDCODALIQFEDERAL  INTEGER NOT NULL,
    BDANO             INTEGER NOT NULL,
    BDALIQUOTAPIS     NUMERIC(15,2) NOT NULL,
    BDALIQUOTACOFINS  NUMERIC(15,2) NOT NULL
);

CREATE TABLE TALIQUOTAICMS (
    BDCODALIQUOTA  INTEGER NOT NULL,
    BDALIQUOTA     NUMERIC(15,2),
    BDCODUF        INTEGER
);

CREATE TABLE TCIDADE (
    BDCODCIDADE   INTEGER NOT NULL,
    BDDESCCIDADE  DM_CIDADE,
    BDCODUF       INTEGER NOT NULL
);

CREATE TABLE TCLIENTE (
    BDCODCLIENTE        INTEGER NOT NULL,
    BDNOMECLIENTE       DM_NOMECLIENTE,
    BDTELEFONECLIENTE   DM_TELEFONE,
    BDENDERECOCLIENTE   DM_ENDERECO,
    BDDOCUMENTOCLIENTE  DM_DOCUMENTOCLIENTE,
    BDCODTIPODOCUMENTO  INTEGER NOT NULL,
    BDCODCIDADE         INTEGER NOT NULL
);

CREATE TABLE TNOTAFISCAL (
    BDCODNOTAFISCAL   INTEGER NOT NULL,
    BDDATAEMISSAO     DATE NOT NULL,
    BDNUMDOCUMENTO    INTEGER NOT NULL,
    BDSERIEDOCUMENTO  INTEGER NOT NULL,
    BDVALORTOTAL      NUMERIC(15,2) NOT NULL,
    BDCODCLIENTE      INTEGER NOT NULL
);

CREATE TABLE TNOTAFISCALITEM (
    BDCODNOTAITEM       INTEGER NOT NULL,
    BDQTDPRODUTO        INTEGER NOT NULL,
    BDPRECOUNITARIO     NUMERIC(15,2) NOT NULL,
    BDVALORTOTALITEM    NUMERIC(15,2) NOT NULL,
    BDCODNOTA           INTEGER NOT NULL,
    BDCODPRODUTO        INTEGER NOT NULL,
    BDIDENTIFCOMERCIAL  INTEGER NOT NULL
);

CREATE TABLE TPRODUTO (
    BDCODPRODUTO        INTEGER NOT NULL,
    BDIDENTIFCOMERCIAL  INTEGER NOT NULL,
    BDDESCPRODUTO       DM_PRODUTO,
    BDPRECOPRODUTO      NUMERIC(15,2) NOT NULL
);

CREATE TABLE TTIPODOCUMENTO (
    BDCODTPDOCUMENTO  INTEGER NOT NULL,
    BDDESCDOCUMENTO   DM_DOCUMENTO
);

CREATE TABLE TUF (
    BDCODUF   INTEGER NOT NULL,
    BDDESCUF  DM_UF
);



/******************************************************************************/
/****                             Primary keys                             ****/
/******************************************************************************/

ALTER TABLE TALIQUOTAFEDERAL ADD CONSTRAINT PK_TALIQUOTAFEDERAL PRIMARY KEY (BDCODALIQFEDERAL);
ALTER TABLE TALIQUOTAICMS ADD CONSTRAINT PK_TALIQUOTAICMS PRIMARY KEY (BDCODALIQUOTA);
ALTER TABLE TCIDADE ADD CONSTRAINT PK_TCIDADE PRIMARY KEY (BDCODCIDADE);
ALTER TABLE TCLIENTE ADD CONSTRAINT PK_TCLIENTE PRIMARY KEY (BDCODCLIENTE);
ALTER TABLE TNOTAFISCAL ADD CONSTRAINT PK_TNOTAFISCAL PRIMARY KEY (BDCODNOTAFISCAL);
ALTER TABLE TNOTAFISCALITEM ADD CONSTRAINT PK_TNOTAFISCALITEM PRIMARY KEY (BDCODNOTAITEM);
ALTER TABLE TPRODUTO ADD CONSTRAINT PK_TPRODUTO PRIMARY KEY (BDCODPRODUTO, BDIDENTIFCOMERCIAL);
ALTER TABLE TTIPODOCUMENTO ADD CONSTRAINT PK_TTIPODOCUMENTO PRIMARY KEY (BDCODTPDOCUMENTO);
ALTER TABLE TUF ADD CONSTRAINT PK_TUF PRIMARY KEY (BDCODUF);


/******************************************************************************/
/****                             Foreign keys                             ****/
/******************************************************************************/

ALTER TABLE TALIQUOTAICMS ADD CONSTRAINT FK_TALIQUOTAICMS_1 FOREIGN KEY (BDCODUF) REFERENCES TUF (BDCODUF);
ALTER TABLE TCIDADE ADD CONSTRAINT FK_TCIDADE_1 FOREIGN KEY (BDCODUF) REFERENCES TUF (BDCODUF);
ALTER TABLE TCLIENTE ADD CONSTRAINT FK_TCLIENTE_1 FOREIGN KEY (BDCODCIDADE) REFERENCES TCIDADE (BDCODCIDADE);
ALTER TABLE TCLIENTE ADD CONSTRAINT FK_TCLIENTE_3 FOREIGN KEY (BDCODTIPODOCUMENTO) REFERENCES TTIPODOCUMENTO (BDCODTPDOCUMENTO);
ALTER TABLE TNOTAFISCAL ADD CONSTRAINT FK_TNOTAFISCAL_1 FOREIGN KEY (BDCODCLIENTE) REFERENCES TCLIENTE (BDCODCLIENTE);
ALTER TABLE TNOTAFISCALITEM ADD CONSTRAINT FK_TNOTAFISCALITEM_1 FOREIGN KEY (BDCODNOTA) REFERENCES TNOTAFISCAL (BDCODNOTAFISCAL);
ALTER TABLE TNOTAFISCALITEM ADD CONSTRAINT FK_TNOTAFISCALITEM_2 FOREIGN KEY (BDCODPRODUTO, BDIDENTIFCOMERCIAL) REFERENCES TPRODUTO (BDCODPRODUTO, BDIDENTIFCOMERCIAL);


/******************************************************************************/
/****                               Triggers                               ****/
/******************************************************************************/



SET TERM ^ ;



/******************************************************************************/
/****                         Triggers for tables                          ****/
/******************************************************************************/



/* Trigger: TALIQUOTAFEDERAL_BI */
CREATE TRIGGER TALIQUOTAFEDERAL_BI FOR TALIQUOTAFEDERAL
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodaliqfederal = gen_id(gen_taliquotafederal_id,1);
end
^

/* Trigger: TALIQUOTAICMS_BI */
CREATE TRIGGER TALIQUOTAICMS_BI FOR TALIQUOTAICMS
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodaliquota = gen_id(gen_taliquotaicms_id,1);
end
^

/* Trigger: TCIDADE_BI */
CREATE TRIGGER TCIDADE_BI FOR TCIDADE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodcidade = gen_id(gen_tcidade_id,1);
end
^

/* Trigger: TCLIENTE_BI */
CREATE TRIGGER TCLIENTE_BI FOR TCLIENTE
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodcliente = gen_id(gen_tcliente_id,1);
end
^

/* Trigger: TNOTAFISCALITEM_BI */
CREATE TRIGGER TNOTAFISCALITEM_BI FOR TNOTAFISCALITEM
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodnotaitem = gen_id(gen_tnotafiscalitem_id,1);
end
^

/* Trigger: TNOTAFISCAL_BI */
CREATE TRIGGER TNOTAFISCAL_BI FOR TNOTAFISCAL
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodnotafiscal = gen_id(gen_tnotafiscal_id,1);
end
^

/* Trigger: TPRODUTO_BI */
CREATE TRIGGER TPRODUTO_BI FOR TPRODUTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodproduto = gen_id(gen_tproduto_id,1);
end
^

/* Trigger: TTIPODOCUMENTO_BI */
CREATE TRIGGER TTIPODOCUMENTO_BI FOR TTIPODOCUMENTO
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcodtpdocumento = gen_id(gen_ttipodocumento_id,1);
end
^

/* Trigger: TUF_BI */
CREATE TRIGGER TUF_BI FOR TUF
ACTIVE BEFORE INSERT POSITION 0
as
begin
  new.bdcoduf = gen_id(gen_tuf_id,1);
end
^
SET TERM ; ^



/******************************************************************************/
/****                          Stored procedures                           ****/
/******************************************************************************/



SET TERM ^ ;

ALTER PROCEDURE SP_APURACAO_IMPOSTOS (
    PR_MES INTEGER,
    PR_ANO INTEGER)
RETURNS (
    BDFATURAMENTOBRUTO NUMERIC(15,2),
    BDTOTALICMS NUMERIC(15,2),
    BDTOTALPIS NUMERIC(15,2),
    BDTOTALCOFINS NUMERIC(15,2))
AS
declare variable WVALOR_ITEM numeric(15,2);
declare variable WVALOR_ICMS numeric(15,2);
declare variable WALIQ_PIS numeric(15,2);
declare variable WALIQ_COFINS numeric(15,2);
begin
  bdfaturamentobruto = 0.0;
  bdtotalicms = 0.0;
  bdtotalpis = 0.0;
  bdtotalcofins = 0.0;

  SELECT FIRST 1
    af.bdaliquotapis,
    af.bdaliquotacofins
  FROM taliquotafederal af
  WHERE af.bdano = :pr_ano
  INTO :waliq_pis, :waliq_cofins;

  FOR
    SELECT
      nfi.bdvalortotalitem,
      COALESCE(ai.bdaliquota, 0.0)
    FROM tnotafiscalitem nfi
    JOIN tnotafiscal n on (n.bdcodnotafiscal = nfi.bdcodnota)
    JOIN tcliente c on (c.bdcodcliente = n.bdcodcliente)
    JOIN tcidade ci on (ci.bdcodcidade = c.bdcodcidade)
    JOIN tuf u on (u.bdcoduf = ci.bdcoduf)
    JOIN taliquotaicms ai on (ai.bdcoduf = u.bdcoduf)
    WHERE EXTRACT(MONTH FROM n.bddataemissao) = :pr_mes
      AND EXTRACT(YEAR FROM n.bddataemissao) = :pr_ano
    INTO :wvalor_item, :wvalor_icms
  DO
  BEGIN
    bdfaturamentobruto = bdfaturamentobruto + wvalor_item;
    bdtotalicms = bdtotalicms + (wvalor_item * (wvalor_icms / 100.0));
  END

  bdtotalcofins = bdfaturamentobruto * (waliq_cofins / 100.0);
  bdtotalpis = bdfaturamentobruto * (waliq_pis / 100.0);
  
  suspend;
end^



SET TERM ; ^

